In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest, f_classif
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score

In [5]:
df = pd.read_csv('/home/dev/Documentos/Teste/Trabalho_base_covid/covid-dataset.csv')

print(df.columns)

X = df.drop(columns=['class'])
y = df['class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Distribuição das classes em y_train:\n", pd.Series(y_train).value_counts())

model_before = DecisionTreeClassifier(random_state=42)
model_before.fit(X_train, y_train)
y_pred_before = model_before.predict(X_train)
print("Matriz de confusão antes do balanceamento:\n", confusion_matrix(y_train, y_pred_before))

Index(['attribute1', 'attribute2', 'attribute3', 'attribute4', 'attribute5',
       'attribute6', 'attribute7', 'attribute8', 'attribute9', 'attribute10',
       'attribute11', 'attribute12', 'attribute13', 'attribute14',
       'attribute15', 'attribute16', 'attribute17', 'attribute18',
       'attribute19', 'attribute20', 'attribute21', 'attribute22',
       'attribute23', 'attribute24', 'attribute25', 'attribute26',
       'attribute27', 'attribute28', 'attribute29', 'attribute30',
       'attribute31', 'attribute32', 'attribute33', 'attribute34',
       'attribute35', 'attribute36', 'attribute37', 'attribute38',
       'attribute39', 'attribute40', 'attribute41', 'attribute42',
       'attribute43', 'attribute44', 'attribute45', 'attribute46',
       'attribute47', 'attribute48', 'attribute49', 'attribute50',
       'attribute51', 'attribute52', 'attribute53', 'attribute54',
       'attribute55', 'attribute56', 'attribute57', 'attribute58',
       'attribute59', 'class'],
      dty

In [6]:
pipeline = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('feature_selection', SelectKBest(score_func=f_classif, k=10)),
    ('smote', SMOTE(k_neighbors=1, random_state=42))
])

X_res, y_res = pipeline.fit_resample(X_train, y_train)

print("Número de amostras após balanceamento:", len(y_res))
print("Distribuição das classes após balanceamento:\n", pd.Series(y_res).value_counts())


model = DecisionTreeClassifier(class_weight='balanced', random_state=42)
model.fit(X_res, y_res)

X_test_transformed = pipeline.named_steps['scaler'].transform(X_test)
X_test_transformed = pipeline.named_steps['feature_selection'].transform(X_test_transformed)

y_pred = model.predict(X_test_transformed)

print("Matriz de confusão após o balanceamento:\n", confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

f1 = f1_score(y_test, y_pred, average='macro')
print(f"F1 Score: {f1:.4f}")


Número de amostras após balanceamento: 1666
Distribuição das classes após balanceamento:
 class
R/Normal                                            238
R/Pneumonia/Celullar/Fungus/Pneumocystis            238
R/Pneumonia/Acellular/Viral/Coronavirus/COVID-19    238
R/Pneumonia/Celullar/Bacterial/Streptococcus        238
R/Pneumonia/Acellular/Viral/Coronavirus/MERS        238
R/Pneumonia/Acellular/Viral/Coronavirus/SARS        238
R/Pneumonia/Acellular/Viral/Varicella               238
Name: count, dtype: int64
Matriz de confusão após o balanceamento:
 [[57  4  0  1  0]
 [ 0  3  1  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  1  0]]
                                                  precision    recall  f1-score   support

                                        R/Normal       1.00      0.92      0.96        62
R/Pneumonia/Acellular/Viral/Coronavirus/COVID-19       0.43      0.75      0.55         4
    R/Pneumonia/Acellular/Viral/Coronavirus/SARS       0.50      1.00      0.67   

/home/dev/Documentos/Teste/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/dev/Documentos/Teste/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/dev/Documentos/Teste/.venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i